var sb = new System.Text.StringBuilder();
var tm = typeof(RNMechs.Simulation.SimulatedMachine);
sb.Append("SimulatedMachine PROPS: ");
foreach (var p in tm.GetProperties()) sb.Append(p.Name + ":" + p.PropertyType.Name + "; ");
sb.Append(" FIELDS: ");
foreach (var f in tm.GetFields()) sb.Append(f.Name + ":" + f.FieldType.Name + "; ");
sb.AppendLine();
var ts = typeof(RNMechs.Simulation.SimulationController);
sb.Append("SimulationController PROPS: ");
foreach (var p in ts.GetProperties()) sb.Append(p.Name + ":" + p.PropertyType.Name + "; ");
sb.Append(" FIELDS: ");
foreach (var f in ts.GetFields()) sb.Append(f.Name + ":" + f.FieldType.Name + "; ");
sb.AppendLine();
var sim = UnityEngine.Object.FindAnyObjectByType<RNMechs.Simulation.SimulationController>();
sb.Append("kaiju type: " + sim.kaiju.GetType().FullName);
return sb.ToString();
