var sb = new System.Text.StringBuilder();
var sim = UnityEngine.Object.FindAnyObjectByType<RNMechs.Simulation.SimulationController>();
var m = sim.LiveMachine;
var part0 = m.Parts[0];
var tp = part0.GetType();
sb.Append("Part type: " + tp.FullName + " PROPS: ");
foreach (var p in tp.GetProperties()) sb.Append(p.Name + ":" + p.PropertyType.Name + "; ");
sb.Append(" FIELDS: ");
foreach (var f in tp.GetFields()) sb.Append(f.Name + ":" + f.FieldType.Name + "; ");
sb.AppendLine();
var tk = sim.kaiju.GetType();
sb.Append("KaijuController PROPS: ");
foreach (var p in tk.GetProperties()) sb.Append(p.Name + ":" + p.PropertyType.Name + "; ");
sb.Append(" FIELDS: ");
foreach (var f in tk.GetFields()) sb.Append(f.Name + ":" + f.FieldType.Name + "; ");
sb.AppendLine();
sb.Append("METHODS: ");
foreach (var mm in tk.GetMethods()) if (!mm.IsSpecialName) sb.Append(mm.Name + "; ");
return sb.ToString();
