var sim = UnityEngine.Object.FindAnyObjectByType<RNMechs.Simulation.SimulationController>();
var m = sim.LiveMachine;
var c = m.ChassisBody;
var fwd = c.transform.forward;
float yaw = Mathf.Atan2(fwd.x, fwd.z) * Mathf.Rad2Deg;
int joints = 0; foreach (var p in m.Parts) if (p.Joint != null) joints++;
var sb = new System.Text.StringBuilder();
sb.Append("t=" + Time.time.ToString("F1"));
sb.Append(" pos=" + c.position.ToString("F2") + " speed=" + c.linearVelocity.magnitude.ToString("F2") + " vel=" + c.linearVelocity.ToString("F1"));
sb.Append(" yaw=" + yaw.ToString("F0") + " angvel=" + c.angularVelocity.magnitude.ToString("F2"));
sb.Append(" joints=" + joints + "/" + m.Parts.Count);
sb.Append(" kHP=" + sim.kaiju.HealthFraction.ToString("P1") + " kpos=" + sim.kaiju.transform.position.ToString("F0"));
sb.Append(" dist=" + Vector3.Distance(c.position, sim.kaiju.transform.position).ToString("F0"));
sb.Append(" breaks=" + RNMechs.Simulation.SimulatedMachine.BreakLog.Count);
return sb.ToString();
