extends "res://tools/render_shots.gd"
## VIL-018 real-plan render gate.  Uses VillageLotPlanner and
## VillageAssembler; no invented building transforms are allowed here.

const OUT := "res://artifacts/p1_acceptance/village_water_actual"

func _init() -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT))
	_build_stage()
	await process_frame
	var only := _only_water()

	# These are all generated by VillageSitePlanner before lot planning.  In
	# particular, do not append a post-lot fixture: that would hide whether the
	# planner kept lots, roads, and enclosure gates out of the water.
	if only == &"" or only == &"pond":
		var pond := _plan(28102, &"farming", &"hedge", &"pond", 30)
		await _shot(pond, "pond_real_roof.jpg", false, 0.72, -0.34)

	if only == &"" or only == &"stream":
		var stream := _plan(28103, &"crossroads", &"none", &"stream", 60)
		await _shot(stream, "stream_real_roof.jpg", false, 0.60, -0.28)
		await _shot(stream, "stream_crossing_close.jpg", false, 0.42, -0.18, true)
		await _shot(stream, "stream_crossing_oblique.jpg", false, 2.35, -0.16, true)

	if only == &"" or only == &"river":
		var river := _plan(28104, &"mill", &"hedge", &"river", 120)
		await _shot(river, "river_real_roof.jpg", false, 0.82, -0.32)
		await _shot(river, "river_crossing_close.jpg", false, 0.42, -0.18, true)

	if only == &"" or only == &"coast":
		var coast := _plan(28105, &"fishing", &"hedge", &"coast", 30)
		await _shot(coast, "coast_real_roof.jpg", false, 0.84, -0.34)

	print("VIL-018 actual-plan renders complete")
	quit()


func _plan(seed: int, purpose: StringName, enclosure: StringName,
		water: StringName, population: int) -> VillagePlan:
	var spec := VillageSpec.new(seed)
	spec.population = population
	spec.purpose = purpose
	spec.culture = &"english"
	spec.enclosure = enclosure
	spec.water = water
	spec.wealth = 0.4
	spec.generate(seed)
	var plan := VillageLotPlanner.plan(spec)
	var crossings := VillageEnclosurePlan.build(plan)["crossings"] as Array
	print("actual plan ", String(water), ": lots=", plan.lots.size(),
		" buildings=", plan.buildings.size(), " water=", plan.water.size(),
		" roads=", plan.roads.size(), " crossings=", crossings.size())
	return plan


func _only_water() -> StringName:
	for arg in OS.get_cmdline_args():
		if String(arg).begins_with("--water="):
			return StringName(String(arg).substr(8))
	return &""


func _shot(plan: VillagePlan, file: String, cutaway: bool,
		yaw: float, pitch: float, close_crossing := false) -> void:
	var node := VillageAssembler.build(plan, cutaway)
	_root3d.add_child(node)
	_colourize(node)
	await process_frame
	var water_centre := plan.site.get_center()
	if not plan.water.is_empty():
		water_centre = Poly.bounding_rect(plan.water[0]["poly"]).get_center()
	var site_centre := plan.site.get_center()
	var focus := site_centre.lerp(water_centre, 0.62)
	if close_crossing:
		var crossings := VillageEnclosurePlan.build(plan)["crossings"] as Array
		for crossing in crossings:
			var road_index: int = int(crossing.get("road", -1))
			if road_index >= 0 and road_index < plan.roads.size() \
					and plan.roads[road_index]["class"] == &"through":
				focus = Vector2(crossing["pos"])
				break
		if close_crossing and focus == site_centre and not crossings.is_empty():
			focus = Vector2(crossings[0]["pos"])
	var centre := Vector3(focus.x, 2.0, focus.y)
	var radius := maxf(plan.site.size.length() * 0.38, 24.0)
	if not plan.water.is_empty() and plan.water[0].get("kind", &"") != &"coast":
		radius = maxf(Poly.bounding_rect(plan.water[0]["poly"]).size.length() * 1.35, 24.0)
	if close_crossing:
		radius = 12.0
		# Stand on the water side of the selected crossing and look slightly
		# down the road so the blue ribbon, ford/bridge deck, and approach are
		# all in one witness frame.
		if water_centre.x > focus.x:
			yaw = PI * 0.5
		else:
			yaw = -PI * 0.5
		pitch = -0.42
	var dist := radius / tan(deg_to_rad(_cam.fov) / 2.0) * 1.05
	var dir := Vector3(sin(yaw) * cos(pitch), -sin(pitch), cos(yaw) * cos(pitch))
	_cam.position = centre + dir * dist
	_cam.look_at(centre, Vector3.UP)
	await _capture_actual(file)
	node.queue_free()


func _capture_actual(file: String) -> void:
	await process_frame
	await RenderingServer.frame_post_draw
	await process_frame
	await RenderingServer.frame_post_draw
	var image: Image = _vp.get_texture().get_image()
	image.save_jpg(OUT + "/" + file, 0.92)
	print("  ", OUT + "/" + file)


func _colourize(node: Node) -> void:
	if node is MeshInstance3D and node.mesh != null:
		var mesh: ArrayMesh = node.mesh
		for i in range(mesh.get_surface_count()):
			if node.name == "Ground":
				var mat := StandardMaterial3D.new()
				mat.albedo_color = Color(VillageBuilder.COLOURS.get(i, "808080"))
				mat.roughness = 0.88
				node.set_surface_override_material(i, mat)
	for child in node.get_children():
		_colourize(child)
